#pragma config(Sensor, in1,    lineFollower1,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  startBump,      sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           lightServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{	robotType(recbot);
		setServo(lightServo, -35);

while(1>0)
  {
     if(SensorValue(startBump) == 1)
    {
					startMotor(leftMotor, 60);
					startMotor(rightMotor, 60);
				}
				untilDark(2850);
					stop();}


}
