#pragma config(Sensor, in1,    lineFollower1,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  startBump,      sensorTouch)
#pragma config(Sensor, dgtl9,  sonarInput1,    sensorSONAR_cm)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           lightServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task forward1(){
	startMotor(leftMotor, 60);
	startMotor(rightMotor, 60);}

task main()
{
	if(SensorValue[dgtl1] == 1){
  	while(1 == 1){
  		setServo(port9, 0);
  		startTask(forward1);}}
  else{
  	stop();
  	if(SensorValue[dgtl9] <= 10){
  		while(SensorValue[dgtl9] <= 10){
  			setServo(port9, -10);
  			setServo(port9, 10);
  				if(nMotorEncoder[port9] < 0){
  					setServo(port9, 0);
  					pointTurn(left, 127);
  					untilLight(10, in1);
  					stop();
  					startTask(forward1);}
  				else{
  		  		setServo(port9, 0);
  					pointTurn(right, 127);
  					untilLight(10, in1);
  					stop();
  					startTask(forward1);}}}}}
