#pragma config(Sensor, in1,    lineFollower1,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  startBump,      sensorTouch)
#pragma config(Sensor, dgtl9,  sonarInput1,    sensorSONAR_cm)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           lightServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task forward1(){
	startMotor(leftMotor, 60);
	startMotor(rightMotor, 60);}

task main()
{
robotType(recbot);
setServo(lightServo, -35);
untilBump(startBump, 10);
startMotor(leftMotor, 60);
startMotor(rightMotor, 60);
untilDark(2850);
stop();



}
