#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

setServo(servo, -35);
wait(5);
setServo(servo, -110);
wait(5);
setServo(servo, -35);
wait(5);
setServo(servo, 75);
wait(5);

}
